export const DATA_ROOT_CANDIDATES = ['data', './data', '../data'];

export const SETTINGS_KEY = 'humanmark-settings';
export const DEFAULT_QUESTIONS_PER_PAGE = 5;
export const MIN_QUESTIONS_PER_PAGE = 1;
export const MAX_QUESTIONS_PER_PAGE = 20;
export const DEFAULT_SORT_NUMERIC_CHOICES = true;

export const CURRENCY_PREFIXES = new Set(['$', '€', '£', '¥', '₹', '₩', '₽', '₺', '₫', '₱', '₪', 'usd', 'eur', 'gbp', 'jpy', 'aud', 'cad', 'cny', 'inr']);
export const SCALE_WORDS = new Map([
	['k', 1_000],
	['thousand', 1_000],
	['m', 1_000_000],
	['million', 1_000_000],
	['b', 1_000_000_000],
	['bn', 1_000_000_000],
	['billion', 1_000_000_000],
	['t', 1_000_000_000_000],
	['tn', 1_000_000_000_000],
	['trillion', 1_000_000_000_000],
]);

export const MEASUREMENT_UNITS = new Map([
	['mm', { dimension: 'length', factor: 0.001 }],
	['millimeter', { dimension: 'length', factor: 0.001 }],
	['millimeters', { dimension: 'length', factor: 0.001 }],
	['cm', { dimension: 'length', factor: 0.01 }],
	['centimeter', { dimension: 'length', factor: 0.01 }],
	['centimeters', { dimension: 'length', factor: 0.01 }],
	['m', { dimension: 'length', factor: 1 }],
	['meter', { dimension: 'length', factor: 1 }],
	['meters', { dimension: 'length', factor: 1 }],
	['km', { dimension: 'length', factor: 1_000 }],
	['kilometer', { dimension: 'length', factor: 1_000 }],
	['kilometers', { dimension: 'length', factor: 1_000 }],
	['in', { dimension: 'length', factor: 0.0254 }],
	['inch', { dimension: 'length', factor: 0.0254 }],
	['inches', { dimension: 'length', factor: 0.0254 }],
	['ft', { dimension: 'length', factor: 0.3048 }],
	['foot', { dimension: 'length', factor: 0.3048 }],
	['feet', { dimension: 'length', factor: 0.3048 }],
	['yd', { dimension: 'length', factor: 0.9144 }],
	['yard', { dimension: 'length', factor: 0.9144 }],
	['yards', { dimension: 'length', factor: 0.9144 }],
	['mi', { dimension: 'length', factor: 1609.344 }],
	['mile', { dimension: 'length', factor: 1609.344 }],
	['miles', { dimension: 'length', factor: 1609.344 }],
	['mg', { dimension: 'mass', factor: 0.001 }],
	['milligram', { dimension: 'mass', factor: 0.001 }],
	['milligrams', { dimension: 'mass', factor: 0.001 }],
	['g', { dimension: 'mass', factor: 1 }],
	['gram', { dimension: 'mass', factor: 1 }],
	['grams', { dimension: 'mass', factor: 1 }],
	['kg', { dimension: 'mass', factor: 1_000 }],
	['kilogram', { dimension: 'mass', factor: 1_000 }],
	['kilograms', { dimension: 'mass', factor: 1_000 }],
	['lb', { dimension: 'mass', factor: 453.59237 }],
	['lbs', { dimension: 'mass', factor: 453.59237 }],
	['pound', { dimension: 'mass', factor: 453.59237 }],
	['pounds', { dimension: 'mass', factor: 453.59237 }],
	['oz', { dimension: 'mass', factor: 28.349523125 }],
	['ounce', { dimension: 'mass', factor: 28.349523125 }],
	['ounces', { dimension: 'mass', factor: 28.349523125 }],
	['ml', { dimension: 'volume', factor: 0.001 }],
	['milliliter', { dimension: 'volume', factor: 0.001 }],
	['milliliters', { dimension: 'volume', factor: 0.001 }],
	['l', { dimension: 'volume', factor: 1 }],
	['liter', { dimension: 'volume', factor: 1 }],
	['liters', { dimension: 'volume', factor: 1 }],
	['s', { dimension: 'time', factor: 1 }],
	['sec', { dimension: 'time', factor: 1 }],
	['secs', { dimension: 'time', factor: 1 }],
	['second', { dimension: 'time', factor: 1 }],
	['seconds', { dimension: 'time', factor: 1 }],
	['min', { dimension: 'time', factor: 60 }],
	['mins', { dimension: 'time', factor: 60 }],
	['minute', { dimension: 'time', factor: 60 }],
	['minutes', { dimension: 'time', factor: 60 }],
	['h', { dimension: 'time', factor: 3600 }],
	['hr', { dimension: 'time', factor: 3600 }],
	['hrs', { dimension: 'time', factor: 3600 }],
	['hour', { dimension: 'time', factor: 3600 }],
	['hours', { dimension: 'time', factor: 3600 }],
]);

export const BARE_LATEX_COMMANDS = new Set([
	'frac',
	'sqrt',
	'cdot',
	'times',
	'leq',
	'geq',
	'neq',
	'approx',
	'pm',
	'mp',
	'alpha',
	'beta',
	'gamma',
	'delta',
	'epsilon',
	'theta',
	'lambda',
	'mu',
	'sigma',
	'pi',
	'phi',
	'psi',
	'omega',
	'sum',
	'prod',
	'int',
	'lim',
	'log',
	'ln',
	'sin',
	'cos',
	'tan',
	'sec',
	'csc',
	'cot',
	'mathrm',
	'mathbf',
	'text',
	'left',
	'right',
	'overline',
	'underline',
	'hat',
	'bar',
	'vec',
	'infty',
]);
